// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAuthToken = `-- name: CreateAuthToken :exec
INSERT INTO auth_token (id, user_id, token_hash, expires_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateAuthTokenParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) error {
	_, err := q.db.Exec(ctx, createAuthToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteAuthTokenByHash = `-- name: DeleteAuthTokenByHash :exec
DELETE FROM auth_token WHERE token_hash = $1
`

func (q *Queries) DeleteAuthTokenByHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteAuthTokenByHash, tokenHash)
	return err
}

const deleteAuthTokensByUserID = `-- name: DeleteAuthTokensByUserID :exec
DELETE FROM auth_token WHERE user_id = $1
`

func (q *Queries) DeleteAuthTokensByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAuthTokensByUserID, userID)
	return err
}

const getAuthTokenByHash = `-- name: GetAuthTokenByHash :one
SELECT id, user_id, token_hash, expires_at, created_at, updated_at
FROM auth_token
WHERE token_hash = $1 AND expires_at > $2
`

type GetAuthTokenByHashParams struct {
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) GetAuthTokenByHash(ctx context.Context, arg GetAuthTokenByHashParams) (AuthToken, error) {
	row := q.db.QueryRow(ctx, getAuthTokenByHash, arg.TokenHash, arg.ExpiresAt)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
