// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: checkpoint.sql

package db

import (
	"context"
)

const getCheckpoint = `-- name: GetCheckpoint :one
SELECT id, last_processed_block, last_processed_tx_index
FROM checkpoint WHERE id = 'default'
`

func (q *Queries) GetCheckpoint(ctx context.Context) (Checkpoint, error) {
	row := q.db.QueryRow(ctx, getCheckpoint)
	var i Checkpoint
	err := row.Scan(&i.ID, &i.LastProcessedBlock, &i.LastProcessedTxIndex)
	return i, err
}

const upsertCheckpoint = `-- name: UpsertCheckpoint :exec
INSERT INTO checkpoint (id, last_processed_block, last_processed_tx_index)
VALUES ('default', $1, $2)
ON CONFLICT (id) DO UPDATE SET
    last_processed_block = EXCLUDED.last_processed_block,
    last_processed_tx_index = EXCLUDED.last_processed_tx_index
`

type UpsertCheckpointParams struct {
	LastProcessedBlock   int64
	LastProcessedTxIndex int
}

func (q *Queries) UpsertCheckpoint(ctx context.Context, arg UpsertCheckpointParams) error {
	_, err := q.db.Exec(ctx, upsertCheckpoint, arg.LastProcessedBlock, arg.LastProcessedTxIndex)
	return err
}
