// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Checkpoint struct {
	ID                   string
	LastProcessedBlock   int64
	LastProcessedTxIndex int
}

type Order struct {
	OrderHash      string
	Maker          string
	MakerIsSellEth bool
	AmountIn       string
	MinAmountOut   string
	DeltaBps       int
	Salt           string
	Deadline       int64
	Signature      []byte
	Status         string
	CreatedAt      time.Time
	FilledAt       pgtype.Timestamp
	CancelledAt    pgtype.Timestamp
	ExpiredAt      pgtype.Timestamp
}

type ProcessedEvent struct {
	EventID string
}

type Trade struct {
	TradeID         string
	Maker           string
	Taker           string
	MakerIsSellEth  bool
	MakerAmountIn   string
	TakerDeposit    string
	DeltaBps        int
	StartTime       int64
	EndTime         int64
	Status          string
	SettlementPrice pgtype.Text
	MakerPayout     pgtype.Text
	TakerPayout     pgtype.Text
	MakerRefund     pgtype.Text
	TakerRefund     pgtype.Text
	CreatedAt       time.Time
	SettledAt       pgtype.Timestamp
	RefundedAt      pgtype.Timestamp
}

type User struct {
	ID        uuid.UUID
	Address   string
	CreatedAt time.Time
	UpdatedAt time.Time
}
