// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: order.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :exec
INSERT INTO orders (
    order_hash, maker, maker_is_sell_eth, amount_in, min_amount_out,
    delta_bps, salt, deadline, signature, status, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
`

type CreateOrderParams struct {
	OrderHash      string
	Maker          string
	MakerIsSellEth bool
	AmountIn       string
	MinAmountOut   string
	DeltaBps       int
	Salt           string
	Deadline       int64
	Signature      []byte
	Status         string
	CreatedAt      time.Time
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) error {
	_, err := q.db.Exec(ctx, createOrder,
		arg.OrderHash,
		arg.Maker,
		arg.MakerIsSellEth,
		arg.AmountIn,
		arg.MinAmountOut,
		arg.DeltaBps,
		arg.Salt,
		arg.Deadline,
		arg.Signature,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const findActiveOrdersBeforeDeadline = `-- name: FindActiveOrdersBeforeDeadline :many
SELECT order_hash, maker, maker_is_sell_eth, amount_in, min_amount_out, delta_bps, salt, deadline, signature, status, created_at, filled_at, cancelled_at, expired_at FROM orders
WHERE status = 'active' AND deadline < $1
ORDER BY deadline ASC
`

func (q *Queries) FindActiveOrdersBeforeDeadline(ctx context.Context, deadline int64) ([]Order, error) {
	rows, err := q.db.Query(ctx, findActiveOrdersBeforeDeadline, deadline)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.OrderHash,
			&i.Maker,
			&i.MakerIsSellEth,
			&i.AmountIn,
			&i.MinAmountOut,
			&i.DeltaBps,
			&i.Salt,
			&i.Deadline,
			&i.Signature,
			&i.Status,
			&i.CreatedAt,
			&i.FilledAt,
			&i.CancelledAt,
			&i.ExpiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOrdersAll = `-- name: FindOrdersAll :many
SELECT order_hash, maker, maker_is_sell_eth, amount_in, min_amount_out, delta_bps, salt, deadline, signature, status, created_at, filled_at, cancelled_at, expired_at FROM orders ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type FindOrdersAllParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) FindOrdersAll(ctx context.Context, arg FindOrdersAllParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, findOrdersAll, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.OrderHash,
			&i.Maker,
			&i.MakerIsSellEth,
			&i.AmountIn,
			&i.MinAmountOut,
			&i.DeltaBps,
			&i.Salt,
			&i.Deadline,
			&i.Signature,
			&i.Status,
			&i.CreatedAt,
			&i.FilledAt,
			&i.CancelledAt,
			&i.ExpiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOrdersByMaker = `-- name: FindOrdersByMaker :many
SELECT order_hash, maker, maker_is_sell_eth, amount_in, min_amount_out, delta_bps, salt, deadline, signature, status, created_at, filled_at, cancelled_at, expired_at FROM orders WHERE maker = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type FindOrdersByMakerParams struct {
	Maker  string
	Limit  int32
	Offset int32
}

func (q *Queries) FindOrdersByMaker(ctx context.Context, arg FindOrdersByMakerParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, findOrdersByMaker, arg.Maker, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.OrderHash,
			&i.Maker,
			&i.MakerIsSellEth,
			&i.AmountIn,
			&i.MinAmountOut,
			&i.DeltaBps,
			&i.Salt,
			&i.Deadline,
			&i.Signature,
			&i.Status,
			&i.CreatedAt,
			&i.FilledAt,
			&i.CancelledAt,
			&i.ExpiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOrdersByStatus = `-- name: FindOrdersByStatus :many
SELECT order_hash, maker, maker_is_sell_eth, amount_in, min_amount_out, delta_bps, salt, deadline, signature, status, created_at, filled_at, cancelled_at, expired_at FROM orders WHERE status = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type FindOrdersByStatusParams struct {
	Status string
	Limit  int32
	Offset int32
}

func (q *Queries) FindOrdersByStatus(ctx context.Context, arg FindOrdersByStatusParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, findOrdersByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.OrderHash,
			&i.Maker,
			&i.MakerIsSellEth,
			&i.AmountIn,
			&i.MinAmountOut,
			&i.DeltaBps,
			&i.Salt,
			&i.Deadline,
			&i.Signature,
			&i.Status,
			&i.CreatedAt,
			&i.FilledAt,
			&i.CancelledAt,
			&i.ExpiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderByHash = `-- name: GetOrderByHash :one
SELECT order_hash, maker, maker_is_sell_eth, amount_in, min_amount_out, delta_bps, salt, deadline, signature, status, created_at, filled_at, cancelled_at, expired_at FROM orders WHERE order_hash = $1
`

func (q *Queries) GetOrderByHash(ctx context.Context, orderHash string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByHash, orderHash)
	var i Order
	err := row.Scan(
		&i.OrderHash,
		&i.Maker,
		&i.MakerIsSellEth,
		&i.AmountIn,
		&i.MinAmountOut,
		&i.DeltaBps,
		&i.Salt,
		&i.Deadline,
		&i.Signature,
		&i.Status,
		&i.CreatedAt,
		&i.FilledAt,
		&i.CancelledAt,
		&i.ExpiredAt,
	)
	return i, err
}

const orderExists = `-- name: OrderExists :one
SELECT EXISTS(SELECT 1 FROM orders WHERE order_hash = $1)
`

func (q *Queries) OrderExists(ctx context.Context, orderHash string) (bool, error) {
	row := q.db.QueryRow(ctx, orderExists, orderHash)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateOrderCancelled = `-- name: UpdateOrderCancelled :exec
UPDATE orders SET status = 'cancelled', cancelled_at = $2 WHERE order_hash = $1
`

type UpdateOrderCancelledParams struct {
	OrderHash   string
	CancelledAt pgtype.Timestamp
}

func (q *Queries) UpdateOrderCancelled(ctx context.Context, arg UpdateOrderCancelledParams) error {
	_, err := q.db.Exec(ctx, updateOrderCancelled, arg.OrderHash, arg.CancelledAt)
	return err
}

const updateOrderExpired = `-- name: UpdateOrderExpired :exec
UPDATE orders SET status = 'expired', expired_at = $2 WHERE order_hash = $1
`

type UpdateOrderExpiredParams struct {
	OrderHash string
	ExpiredAt pgtype.Timestamp
}

func (q *Queries) UpdateOrderExpired(ctx context.Context, arg UpdateOrderExpiredParams) error {
	_, err := q.db.Exec(ctx, updateOrderExpired, arg.OrderHash, arg.ExpiredAt)
	return err
}

const updateOrderFilled = `-- name: UpdateOrderFilled :exec
UPDATE orders SET status = 'filled', filled_at = $2 WHERE order_hash = $1
`

type UpdateOrderFilledParams struct {
	OrderHash string
	FilledAt  pgtype.Timestamp
}

func (q *Queries) UpdateOrderFilled(ctx context.Context, arg UpdateOrderFilledParams) error {
	_, err := q.db.Exec(ctx, updateOrderFilled, arg.OrderHash, arg.FilledAt)
	return err
}
