// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: processed_events.sql

package db

import (
	"context"
)

const insertProcessedEvent = `-- name: InsertProcessedEvent :exec
INSERT INTO processed_events (event_id) VALUES ($1)
`

func (q *Queries) InsertProcessedEvent(ctx context.Context, eventID string) error {
	_, err := q.db.Exec(ctx, insertProcessedEvent, eventID)
	return err
}

const processedEventExists = `-- name: ProcessedEventExists :one
SELECT EXISTS(SELECT 1 FROM processed_events WHERE event_id = $1)
`

func (q *Queries) ProcessedEventExists(ctx context.Context, eventID string) (bool, error) {
	row := q.db.QueryRow(ctx, processedEventExists, eventID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
