// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: trade.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTrade = `-- name: CreateTrade :exec
INSERT INTO trades (
    trade_id, maker, taker, maker_is_sell_eth, maker_amount_in, taker_deposit,
    delta_bps, start_time, end_time, status, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
`

type CreateTradeParams struct {
	TradeID        string
	Maker          string
	Taker          string
	MakerIsSellEth bool
	MakerAmountIn  string
	TakerDeposit   string
	DeltaBps       int
	StartTime      int64
	EndTime        int64
	Status         string
	CreatedAt      time.Time
}

func (q *Queries) CreateTrade(ctx context.Context, arg CreateTradeParams) error {
	_, err := q.db.Exec(ctx, createTrade,
		arg.TradeID,
		arg.Maker,
		arg.Taker,
		arg.MakerIsSellEth,
		arg.MakerAmountIn,
		arg.TakerDeposit,
		arg.DeltaBps,
		arg.StartTime,
		arg.EndTime,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const findTradesByAddress = `-- name: FindTradesByAddress :many
SELECT trade_id, maker, taker, maker_is_sell_eth, maker_amount_in, taker_deposit, delta_bps, start_time, end_time, status, settlement_price, maker_payout, taker_payout, maker_refund, taker_refund, created_at, settled_at, refunded_at FROM trades
WHERE maker = $1 OR taker = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type FindTradesByAddressParams struct {
	Maker  string
	Limit  int32
	Offset int32
}

func (q *Queries) FindTradesByAddress(ctx context.Context, arg FindTradesByAddressParams) ([]Trade, error) {
	rows, err := q.db.Query(ctx, findTradesByAddress, arg.Maker, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trade{}
	for rows.Next() {
		var i Trade
		if err := rows.Scan(
			&i.TradeID,
			&i.Maker,
			&i.Taker,
			&i.MakerIsSellEth,
			&i.MakerAmountIn,
			&i.TakerDeposit,
			&i.DeltaBps,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.SettlementPrice,
			&i.MakerPayout,
			&i.TakerPayout,
			&i.MakerRefund,
			&i.TakerRefund,
			&i.CreatedAt,
			&i.SettledAt,
			&i.RefundedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findTradesByAddressAndStatus = `-- name: FindTradesByAddressAndStatus :many
SELECT trade_id, maker, taker, maker_is_sell_eth, maker_amount_in, taker_deposit, delta_bps, start_time, end_time, status, settlement_price, maker_payout, taker_payout, maker_refund, taker_refund, created_at, settled_at, refunded_at FROM trades
WHERE (maker = $1 OR taker = $1) AND status = $2
ORDER BY created_at DESC LIMIT $3 OFFSET $4
`

type FindTradesByAddressAndStatusParams struct {
	Maker  string
	Status string
	Limit  int32
	Offset int32
}

func (q *Queries) FindTradesByAddressAndStatus(ctx context.Context, arg FindTradesByAddressAndStatusParams) ([]Trade, error) {
	rows, err := q.db.Query(ctx, findTradesByAddressAndStatus,
		arg.Maker,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trade{}
	for rows.Next() {
		var i Trade
		if err := rows.Scan(
			&i.TradeID,
			&i.Maker,
			&i.Taker,
			&i.MakerIsSellEth,
			&i.MakerAmountIn,
			&i.TakerDeposit,
			&i.DeltaBps,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.SettlementPrice,
			&i.MakerPayout,
			&i.TakerPayout,
			&i.MakerRefund,
			&i.TakerRefund,
			&i.CreatedAt,
			&i.SettledAt,
			&i.RefundedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findTradesByStatus = `-- name: FindTradesByStatus :many
SELECT trade_id, maker, taker, maker_is_sell_eth, maker_amount_in, taker_deposit, delta_bps, start_time, end_time, status, settlement_price, maker_payout, taker_payout, maker_refund, taker_refund, created_at, settled_at, refunded_at FROM trades
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type FindTradesByStatusParams struct {
	Status string
	Limit  int32
	Offset int32
}

func (q *Queries) FindTradesByStatus(ctx context.Context, arg FindTradesByStatusParams) ([]Trade, error) {
	rows, err := q.db.Query(ctx, findTradesByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trade{}
	for rows.Next() {
		var i Trade
		if err := rows.Scan(
			&i.TradeID,
			&i.Maker,
			&i.Taker,
			&i.MakerIsSellEth,
			&i.MakerAmountIn,
			&i.TakerDeposit,
			&i.DeltaBps,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.SettlementPrice,
			&i.MakerPayout,
			&i.TakerPayout,
			&i.MakerRefund,
			&i.TakerRefund,
			&i.CreatedAt,
			&i.SettledAt,
			&i.RefundedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTradeById = `-- name: GetTradeById :one
SELECT trade_id, maker, taker, maker_is_sell_eth, maker_amount_in, taker_deposit, delta_bps, start_time, end_time, status, settlement_price, maker_payout, taker_payout, maker_refund, taker_refund, created_at, settled_at, refunded_at FROM trades WHERE trade_id = $1
`

func (q *Queries) GetTradeById(ctx context.Context, tradeID string) (Trade, error) {
	row := q.db.QueryRow(ctx, getTradeById, tradeID)
	var i Trade
	err := row.Scan(
		&i.TradeID,
		&i.Maker,
		&i.Taker,
		&i.MakerIsSellEth,
		&i.MakerAmountIn,
		&i.TakerDeposit,
		&i.DeltaBps,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.SettlementPrice,
		&i.MakerPayout,
		&i.TakerPayout,
		&i.MakerRefund,
		&i.TakerRefund,
		&i.CreatedAt,
		&i.SettledAt,
		&i.RefundedAt,
	)
	return i, err
}

const updateTradeRefunded = `-- name: UpdateTradeRefunded :exec
UPDATE trades
SET status = 'refunded', maker_refund = $2, taker_refund = $3, refunded_at = $4
WHERE trade_id = $1
`

type UpdateTradeRefundedParams struct {
	TradeID     string
	MakerRefund pgtype.Text
	TakerRefund pgtype.Text
	RefundedAt  pgtype.Timestamp
}

func (q *Queries) UpdateTradeRefunded(ctx context.Context, arg UpdateTradeRefundedParams) error {
	_, err := q.db.Exec(ctx, updateTradeRefunded,
		arg.TradeID,
		arg.MakerRefund,
		arg.TakerRefund,
		arg.RefundedAt,
	)
	return err
}

const updateTradeSettled = `-- name: UpdateTradeSettled :exec
UPDATE trades
SET status = 'settled', settlement_price = $2, maker_payout = $3, taker_payout = $4,
    maker_refund = $5, taker_refund = $6, settled_at = $7
WHERE trade_id = $1
`

type UpdateTradeSettledParams struct {
	TradeID         string
	SettlementPrice pgtype.Text
	MakerPayout     pgtype.Text
	TakerPayout     pgtype.Text
	MakerRefund     pgtype.Text
	TakerRefund     pgtype.Text
	SettledAt       pgtype.Timestamp
}

func (q *Queries) UpdateTradeSettled(ctx context.Context, arg UpdateTradeSettledParams) error {
	_, err := q.db.Exec(ctx, updateTradeSettled,
		arg.TradeID,
		arg.SettlementPrice,
		arg.MakerPayout,
		arg.TakerPayout,
		arg.MakerRefund,
		arg.TakerRefund,
		arg.SettledAt,
	)
	return err
}
