// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getUser = `-- name: GetUser :one
SELECT id, address, created_at, updated_at FROM "user" WHERE "id" = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByAddress = `-- name: GetUserByAddress :one
SELECT id, address, created_at, updated_at FROM "user" WHERE "address" = $1
`

func (q *Queries) GetUserByAddress(ctx context.Context, address string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAddress, address)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO "user" ("id", "address", "created_at", "updated_at")
VALUES ($1, $2, $3, $4)
`

type InsertUserParams struct {
	ID        uuid.UUID
	Address   string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.Exec(ctx, insertUser,
		arg.ID,
		arg.Address,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listUsers = `-- name: ListUsers :many
SELECT "id" FROM "user"
`

func (q *Queries) ListUsers(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
